apiVersion: v2
name: datahub
description: A Helm chart for DataHub
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.6.13

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: v1.1.0
dependencies:
  - name: datahub-gms
    version: 0.2.186
    repository: file://./subcharts/datahub-gms
    condition: datahub-gms.enabled
  - name: datahub-frontend
    version: 0.2.163
    repository: file://./subcharts/datahub-frontend
    condition: datahub-frontend.enabled
  - name: acryl-datahub-actions
    version: 0.2.152
    repository: file://./subcharts/acryl-datahub-actions
    condition: acryl-datahub-actions.enabled
maintainers:
  - name: DataHub
    email: datahub@acryl.io