insert into edl_dq_rules(rule_name, control_name, rule_desc, rule_example)
values ('hasSize', 'Conformity', null, 'hasSize(_ == 5)'),
('isComplete', 'Conformity', null, 'isComplete(ColumnName)'),
('isUnique', 'Uniqueness', null, 'isUnique(ColumnName)'),
('isNonNegative', 'Completeness', null, 'isNonNegative(ColumnName)'),
('isContainedIn', 'Conformity', null, '.isContainedIn(“ColumnName”, Array(array list comma separated))'),
('hasUniqueness', 'Uniqueness', null, 'hasUniqueness(“ColumnName”, _ ==1.0)'),
('hasDistinctness', 'Uniqueness', null, 'hasDistinctness(“ColumnName”, _ ==1.0)'),
('hasUniqueValueRatio', 'Uniqueness', null, 'hasUniqueValueRatio()'),
('hasMutualInformation', 'Uniqueness', null, 'hasMutualInformation()'),
('hasApproxQuantile', 'Conformity', null, 'hasApproxQuantile()'),
('hasMinLength', 'Completeness', null, 'hasMinLength()'),
('hasMaxLength', 'Completeness', null, 'hasMaxLength()'),
('hasMin', 'Completeness', null, 'hasMin(“ColumnName”, _ ==1.0)'),
('hasMax', 'Completeness', null, 'hasMax(“ColumnName”, _ ==5.0)'),
('hasMean', 'Completeness', null, 'hasMean(“ColumnName”, _ ==5.0)'),
('hasSum', 'Completeness', null, 'hasSum(“ColumnName”, _ ==5.0)'),
('hasStandardDeviation', 'Completeness', null, 'hasStandardDeviation()'),
('hasApproxCountDistinct', 'Completeness', null, 'hasApproxCountDistinct()'),
('containsCreditCardNumber', 'Completeness', null, 'containsCreditCardNumber("ColumnName”)'),
('containsEmail', 'Completeness', null, 'containsEmail("ColumnName”)'),
('containsURL', 'Completeness', null, 'containsURL("ColumnName”)'),
('containsSocialSecurityNumber', 'Completeness', null, 'containsSocialSecurityNumber()'),
('hasDataType', 'Conformity', null, 'hasDataType(“ColumnName”, Boolean)'),
('isNonNegative', 'Completeness', null, 'isNonNegative()'),
('isPositive', 'Completeness', null, 'isPositive()'),
('isLessThan', 'Completeness', null, 'isLessThan(“ColumnName”, “ColumnName”)'),
('isLessThanOrEqualTo', 'Completeness', null, 'isLessThanOrEqualTo(“ColumnName”, “ColumnName”)'),
('isGreaterThan', 'Completeness', null, 'isGreaterThan(“ColumnName”, “ColumnName”)'),
('isGreaterThanOrEqualTo', 'Completeness', null, 'isGreaterThanOrEqualTo(“ColumnName”, “ColumnName”)') ON CONFLICT DO NOTHING;
